use_frameworks!


target 'TYSMBaseKit_Example' do
  platform :ios, '11.0'

  pod 'TYSMBaseKit', :path => '../'

  target 'TYSMBaseKit_Tests' do
    inherit! :search_paths

    
  end
end

target 'TYSMBaseKit_Macos' do
  platform :osx, '10.14'
  pod 'TYSMBaseKit', :path => '../'

end
